### ISSUE TITLE
Authentication refinement.

### ISSUE THREAD

**Issue by vogdb** [cargomedia/pulsar-rest-api#40]
- Should be config option `githubOrg` required? May be we do like this: if it is presented then we include membership checking in authentication process otherwise authentication goes without membership checking.
- May be we should make config options `githubOauthId` and `githubOauthSecret` optional? Because some users don't want to store their credentials in some file. [Github-oauth library](https://github.com/maxogden/github-oauth#usage) does like this through the `process.env['GITHUB_CLIENT']` and `process.env['GITHUB_SECRET']` variables.

@njam @tomaszdurka @kris-lab what do you think?

**Comment by njam** [comment]
Closing for now.
