### ISSUE TITLE
Meta: future list

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/pulsar-rest-api#45]
#### web interface
- add form field input as `stdin` under/below each output for task `stdout + stderr`; it will allow for two directional communication with process;
#### server
- add possibility to detect prompt from spawn process; allow to send user respond to server-pulsar-process
- logger: make it working with `logrotate`; should not fails if the log file is moved or removed; log4js file rotation handler should be replaced with single flat file handler;
#### hubot-pulsar
- adjust hubot-pulsar to allow send `stdin` to server-pulsar-process
- config: extend to read `ENV` value to get correct path (will be installed by puppet)
- extend config with `include` for permissions file? (will be done by puppet); `/etc/hubot/plugins/hubot-pulsar/permissions.conf` ?
- on start/restart read permissions file and apply?

@vogdb please have a look

**Comment by njam** [comment]
Closing for now.
