### ISSUE TITLE
Support for upcoming Pulsar version with support for Capistrano 3

### ISSUE THREAD

**Issue by mtylty** [cargomedia/pulsar-rest-api#91]
Hi guys,

just a heads up, I'm almost done coding support for Capistrano 3 in Pulsar.

Considering how much Capistrano 3 is different from Capistrano 2 we decided to drop support for Capistrano 2.

I'll release a new Pulsar version (probably version `1.0.0`) and that will land on master. Pulsar `0.3` version will not be supported anymore.

Eventually [this branch](https://github.com/nebulab/pulsar/tree/capistrano-3) will end up in `master`.

Just a heads up in case you're using something from the current `master` with the old Capistrano 2 Pulsar version. Feel free to close this if this is not an issue for you.

**Comment by njam** [comment]
Thanks for the heads up!

We will definitely test it. It will take us a bit to adapt the deploy recipe I imagine, as we have quite a few customizations.

(moving to https://youtrack.cargomedia.ch/issue/BO-137)
